[package]
name = "nes"
version = "0.1.0"
authors = ["Matt Wallick <mcwallick@gmail.com>"]
edition = "2018"

[dependencies]

[lib]
name = "fenes"
path = "src/lib.rs"

[[bin]]
name = "fenesbin"
path = "src/main.rs"